# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt/batch_features.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_FeatureDialog(object):
    def setupUi(self, FeatureDialog):
        FeatureDialog.setObjectName("FeatureDialog")
        FeatureDialog.resize(568, 620)
        self.gridLayout = QtWidgets.QGridLayout(FeatureDialog)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem, 6, 0, 1, 3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.start_button = QtWidgets.QPushButton(FeatureDialog)
        self.start_button.setMaximumSize(QtCore.QSize(80, 16777215))
        self.start_button.setObjectName("start_button")
        self.horizontalLayout.addWidget(self.start_button)
        self.close_button = QtWidgets.QPushButton(FeatureDialog)
        self.close_button.setMaximumSize(QtCore.QSize(80, 16777215))
        self.close_button.setObjectName("close_button")
        self.horizontalLayout.addWidget(self.close_button)
        self.gridLayout.addLayout(self.horizontalLayout, 9, 0, 1, 3)
        self.checkbox_layout = QtWidgets.QVBoxLayout()
        self.checkbox_layout.setObjectName("checkbox_layout")
        self.gridLayout.addLayout(self.checkbox_layout, 8, 0, 1, 3)
        self.groupBox = QtWidgets.QGroupBox(FeatureDialog)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 250))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.image_queue_text = QtWidgets.QTextEdit(self.groupBox)
        self.image_queue_text.setReadOnly(True)
        self.image_queue_text.setObjectName("image_queue_text")
        self.verticalLayout_2.addWidget(self.image_queue_text)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.clear_button = QtWidgets.QPushButton(self.groupBox)
        self.clear_button.setMaximumSize(QtCore.QSize(40, 16777215))
        self.clear_button.setObjectName("clear_button")
        self.horizontalLayout_2.addWidget(self.clear_button)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.gridLayout.addWidget(self.groupBox, 3, 0, 1, 3)
        self.features_box = QtWidgets.QGroupBox(FeatureDialog)
        self.features_box.setMinimumSize(QtCore.QSize(0, 150))
        self.features_box.setObjectName("features_box")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.features_box)
        self.verticalLayout.setObjectName("verticalLayout")
        self.features_list = QtWidgets.QListWidget(self.features_box)
        self.features_list.setObjectName("features_list")
        self.verticalLayout.addWidget(self.features_list)
        self.gridLayout.addWidget(self.features_box, 7, 0, 1, 3)
        self.button_layout = QtWidgets.QHBoxLayout()
        self.button_layout.setObjectName("button_layout")
        self.images_browse_button = QtWidgets.QPushButton(FeatureDialog)
        self.images_browse_button.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.images_browse_button.setObjectName("images_browse_button")
        self.button_layout.addWidget(self.images_browse_button)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.button_layout.addItem(spacerItem3)
        self.gridLayout.addLayout(self.button_layout, 5, 0, 1, 3)
        self.label_2 = QtWidgets.QLabel(FeatureDialog)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)

        self.retranslateUi(FeatureDialog)
        QtCore.QMetaObject.connectSlotsByName(FeatureDialog)

    def retranslateUi(self, FeatureDialog):
        _translate = QtCore.QCoreApplication.translate
        FeatureDialog.setWindowTitle(_translate("FeatureDialog", "Extract Features"))
        self.start_button.setText(_translate("FeatureDialog", "Start"))
        self.close_button.setText(_translate("FeatureDialog", "Close"))
        self.groupBox.setTitle(_translate("FeatureDialog", "Imagequeue"))
        self.label.setText(_translate("FeatureDialog", "↑↑↑ drag & drop"))
        self.clear_button.setText(_translate("FeatureDialog", "clear"))
        self.features_box.setTitle(_translate("FeatureDialog", "Features"))
        self.images_browse_button.setText(_translate("FeatureDialog", "Add Images to Queue"))
        self.label_2.setText(_translate("FeatureDialog", "Advice: Use already segmented images only!"))

