# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt/extract_features.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_FeatureDialog(object):
    def setupUi(self, FeatureDialog):
        FeatureDialog.setObjectName("FeatureDialog")
        FeatureDialog.resize(568, 631)
        self.gridLayout = QtWidgets.QGridLayout(FeatureDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.replace_check = QtWidgets.QCheckBox(FeatureDialog)
        self.replace_check.setChecked(True)
        self.replace_check.setObjectName("replace_check")
        self.gridLayout.addWidget(self.replace_check, 9, 0, 1, 3)
        self.crop_check = QtWidgets.QCheckBox(FeatureDialog)
        self.crop_check.setObjectName("crop_check")
        self.gridLayout.addWidget(self.crop_check, 10, 0, 1, 3)
        self.groupBox = QtWidgets.QGroupBox(FeatureDialog)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 250))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(self.groupBox)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 530, 217))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.image_queue_text = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.image_queue_text.setReadOnly(True)
        self.image_queue_text.setObjectName("image_queue_text")
        self.verticalLayout_3.addWidget(self.image_queue_text)
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollArea)
        self.gridLayout.addWidget(self.groupBox, 3, 0, 1, 3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.start_button = QtWidgets.QPushButton(FeatureDialog)
        self.start_button.setMaximumSize(QtCore.QSize(80, 16777215))
        self.start_button.setObjectName("start_button")
        self.horizontalLayout.addWidget(self.start_button)
        self.close_button = QtWidgets.QPushButton(FeatureDialog)
        self.close_button.setMaximumSize(QtCore.QSize(80, 16777215))
        self.close_button.setObjectName("close_button")
        self.horizontalLayout.addWidget(self.close_button)
        self.gridLayout.addLayout(self.horizontalLayout, 12, 0, 1, 3)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 11, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem2, 6, 0, 1, 3)
        self.features_box = QtWidgets.QGroupBox(FeatureDialog)
        self.features_box.setMinimumSize(QtCore.QSize(0, 150))
        self.features_box.setObjectName("features_box")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.features_box)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.features_box)
        self.scrollArea_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 530, 183))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.features_list = QtWidgets.QListWidget(self.scrollAreaWidgetContents_2)
        self.features_list.setObjectName("features_list")
        self.verticalLayout_4.addWidget(self.features_list)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout.addWidget(self.scrollArea_2)
        self.gridLayout.addWidget(self.features_box, 7, 0, 1, 3)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 5, 1, 1, 1)
        self.images_browse_button = QtWidgets.QPushButton(FeatureDialog)
        self.images_browse_button.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.images_browse_button.setObjectName("images_browse_button")
        self.gridLayout.addWidget(self.images_browse_button, 5, 0, 1, 1)

        self.retranslateUi(FeatureDialog)
        QtCore.QMetaObject.connectSlotsByName(FeatureDialog)

    def retranslateUi(self, FeatureDialog):
        _translate = QtCore.QCoreApplication.translate
        FeatureDialog.setWindowTitle(_translate("FeatureDialog", "Extract Features"))
        self.replace_check.setText(_translate("FeatureDialog", "replace existing feature/species combinations in store"))
        self.crop_check.setText(_translate("FeatureDialog", "segment and crop the images, before extracting the features (not needed if already cropped)"))
        self.groupBox.setTitle(_translate("FeatureDialog", "Imagequeue"))
        self.label.setText(_translate("FeatureDialog", "↑↑↑ drag & drop"))
        self.start_button.setText(_translate("FeatureDialog", "Start"))
        self.close_button.setText(_translate("FeatureDialog", "Close"))
        self.features_box.setTitle(_translate("FeatureDialog", "Features"))
        self.images_browse_button.setText(_translate("FeatureDialog", "Add Images of Species to Queue"))

