# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt/main_window.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(946, 638)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.tabWidget.setPalette(palette)
        self.tabWidget.setObjectName("tabWidget")
        self.preprocessing_tab = QtWidgets.QWidget()
        self.preprocessing_tab.setObjectName("preprocessing_tab")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.preprocessing_tab)
        self.gridLayout_4.setContentsMargins(15, 15, 15, 15)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.zoom_slider = QtWidgets.QSlider(self.preprocessing_tab)
        self.zoom_slider.setMinimum(1)
        self.zoom_slider.setMaximum(50)
        self.zoom_slider.setOrientation(QtCore.Qt.Vertical)
        self.zoom_slider.setObjectName("zoom_slider")
        self.gridLayout_4.addWidget(self.zoom_slider, 3, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_4.addItem(spacerItem, 1, 0, 1, 1)
        self.scrollArea_2 = QtWidgets.QScrollArea(self.preprocessing_tab)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.scrollArea_2.setPalette(palette)
        self.scrollArea_2.setAutoFillBackground(False)
        self.scrollArea_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_4 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 1654, 506))
        self.scrollAreaWidgetContents_4.setObjectName("scrollAreaWidgetContents_4")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_4)
        self.gridLayout_11.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.preprocess_steps_combo = QtWidgets.QComboBox(self.scrollAreaWidgetContents_4)
        self.preprocess_steps_combo.setObjectName("preprocess_steps_combo")
        self.gridLayout_11.addWidget(self.preprocess_steps_combo, 5, 6, 1, 2)
        self.preprocessor_combo = QtWidgets.QComboBox(self.scrollAreaWidgetContents_4)
        self.preprocessor_combo.setObjectName("preprocessor_combo")
        self.gridLayout_11.addWidget(self.preprocessor_combo, 1, 6, 1, 1)
        self.preprocess_button = QtWidgets.QPushButton(self.scrollAreaWidgetContents_4)
        self.preprocess_button.setMaximumSize(QtCore.QSize(100, 16777215))
        self.preprocess_button.setObjectName("preprocess_button")
        self.gridLayout_11.addWidget(self.preprocess_button, 1, 7, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem1, 3, 5, 1, 1)
        self.source_image_scroll = QtWidgets.QScrollArea(self.scrollAreaWidgetContents_4)
        self.source_image_scroll.setMinimumSize(QtCore.QSize(500, 300))
        self.source_image_scroll.setWidgetResizable(True)
        self.source_image_scroll.setObjectName("source_image_scroll")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 498, 393))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.source_label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.source_label.setAlignment(QtCore.Qt.AlignCenter)
        self.source_label.setObjectName("source_label")
        self.gridLayout.addWidget(self.source_label, 0, 1, 1, 1)
        self.source_image_scroll.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_11.addWidget(self.source_image_scroll, 3, 1, 2, 4)
        self.feature_combo = QtWidgets.QComboBox(self.scrollAreaWidgetContents_4)
        self.feature_combo.setObjectName("feature_combo")
        self.gridLayout_11.addWidget(self.feature_combo, 1, 9, 1, 1)
        self.scrollArea_3 = QtWidgets.QScrollArea(self.scrollAreaWidgetContents_4)
        self.scrollArea_3.setMinimumSize(QtCore.QSize(500, 300))
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_5 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_5.setGeometry(QtCore.QRect(0, 0, 498, 367))
        self.scrollAreaWidgetContents_5.setObjectName("scrollAreaWidgetContents_5")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_5)
        self.gridLayout_12.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.feature_label = QtWidgets.QLabel(self.scrollAreaWidgetContents_5)
        self.feature_label.setAlignment(QtCore.Qt.AlignCenter)
        self.feature_label.setObjectName("feature_label")
        self.gridLayout_12.addWidget(self.feature_label, 0, 1, 1, 1)
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_5)
        self.gridLayout_11.addWidget(self.scrollArea_3, 3, 9, 1, 2)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem2, 3, 8, 1, 1)
        self.feature_steps_combo = QtWidgets.QComboBox(self.scrollAreaWidgetContents_4)
        self.feature_steps_combo.setObjectName("feature_steps_combo")
        self.gridLayout_11.addWidget(self.feature_steps_combo, 5, 9, 1, 2)
        self.pushButton_3 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_4)
        self.pushButton_3.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_11.addWidget(self.pushButton_3, 1, 10, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem3, 1, 11, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_11.addWidget(self.label_6, 0, 6, 1, 2)
        self.label_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_11.addWidget(self.label_5, 0, 1, 1, 4)
        self.scrollArea = QtWidgets.QScrollArea(self.scrollAreaWidgetContents_4)
        self.scrollArea.setMinimumSize(QtCore.QSize(500, 300))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 498, 393))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.preprocess_label = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.preprocess_label.setAlignment(QtCore.Qt.AlignCenter)
        self.preprocess_label.setObjectName("preprocess_label")
        self.gridLayout_3.addWidget(self.preprocess_label, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout_11.addWidget(self.scrollArea, 3, 6, 2, 2)
        self.label_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_11.addWidget(self.label_7, 0, 9, 1, 2)
        self.open_source_button = QtWidgets.QPushButton(self.scrollAreaWidgetContents_4)
        self.open_source_button.setMaximumSize(QtCore.QSize(100, 16777215))
        self.open_source_button.setObjectName("open_source_button")
        self.gridLayout_11.addWidget(self.open_source_button, 1, 4, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem4, 3, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_11.addItem(spacerItem5, 6, 9, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_4)
        self.lineEdit.setEnabled(True)
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_11.addWidget(self.lineEdit, 4, 9, 1, 2)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem6, 1, 3, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        self.label_8.setObjectName("label_8")
        self.gridLayout_11.addWidget(self.label_8, 5, 4, 1, 1)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_4)
        self.gridLayout_4.addWidget(self.scrollArea_2, 1, 1, 4, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_4.addItem(spacerItem7, 4, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.preprocessing_tab)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 2, 0, 1, 1)
        self.tabWidget.addTab(self.preprocessing_tab, "")
        self.training_tab = QtWidgets.QWidget()
        self.training_tab.setObjectName("training_tab")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.training_tab)
        self.gridLayout_5.setContentsMargins(15, 15, 15, 15)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.line = QtWidgets.QFrame(self.training_tab)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_5.addWidget(self.line, 0, 2, 10, 1)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem8, 3, 5, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem9, 2, 1, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem10, 2, 3, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.training_tab)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_8.addWidget(self.pushButton_2, 0, 0, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem11, 0, 1, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox_2, 2, 4, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.training_tab)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.train_button = QtWidgets.QPushButton(self.groupBox_3)
        self.train_button.setObjectName("train_button")
        self.gridLayout_9.addWidget(self.train_button, 2, 0, 1, 1)
        self.classifier_combo = QtWidgets.QComboBox(self.groupBox_3)
        self.classifier_combo.setObjectName("classifier_combo")
        self.gridLayout_9.addWidget(self.classifier_combo, 1, 0, 1, 2)
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        self.label_3.setObjectName("label_3")
        self.gridLayout_9.addWidget(self.label_3, 0, 0, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem12, 2, 1, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox_3, 3, 4, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.training_tab)
        self.groupBox.setMinimumSize(QtCore.QSize(400, 0))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.delete_button = QtWidgets.QPushButton(self.groupBox)
        self.delete_button.setObjectName("delete_button")
        self.gridLayout_7.addWidget(self.delete_button, 3, 4, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem13, 3, 1, 1, 2)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout_7.addWidget(self.label, 4, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout_7.addWidget(self.label_2, 0, 1, 1, 1)
        self.checkBox_2 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_2.setObjectName("checkBox_2")
        self.gridLayout_7.addWidget(self.checkBox_2, 1, 1, 1, 1)
        self.species_list = QtWidgets.QListWidget(self.groupBox)
        self.species_list.setObjectName("species_list")
        self.gridLayout_7.addWidget(self.species_list, 6, 1, 1, 4)
        self.features_list = QtWidgets.QListWidget(self.groupBox)
        self.features_list.setObjectName("features_list")
        self.gridLayout_7.addWidget(self.features_list, 2, 1, 1, 4)
        self.checkBox = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout_7.addWidget(self.checkBox, 5, 1, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_7.addWidget(self.pushButton_4, 7, 4, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem14, 7, 1, 1, 3)
        self.add_feature_button = QtWidgets.QPushButton(self.groupBox)
        self.add_feature_button.setObjectName("add_feature_button")
        self.gridLayout_7.addWidget(self.add_feature_button, 3, 3, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox, 2, 0, 4, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.training_tab)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_5.addWidget(self.groupBox_4, 4, 4, 2, 1)
        self.tabWidget.addTab(self.training_tab, "")
        self.prediction_tab = QtWidgets.QWidget()
        self.prediction_tab.setObjectName("prediction_tab")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.prediction_tab)
        self.gridLayout_6.setContentsMargins(15, 15, 15, 15)
        self.gridLayout_6.setObjectName("gridLayout_6")
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem15, 0, 1, 1, 1)
        self.listWidget_3 = QtWidgets.QListWidget(self.prediction_tab)
        self.listWidget_3.setObjectName("listWidget_3")
        self.gridLayout_6.addWidget(self.listWidget_3, 0, 0, 1, 1)
        self.tabWidget.addTab(self.prediction_tab, "")
        self.gridLayout_2.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 946, 21))
        self.menubar.setObjectName("menubar")
        self.menuDatei = QtWidgets.QMenu(self.menubar)
        self.menuDatei.setObjectName("menuDatei")
        self.menuBatch = QtWidgets.QMenu(self.menubar)
        self.menuBatch.setObjectName("menuBatch")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionBild_ffnen = QtWidgets.QAction(MainWindow)
        self.actionBild_ffnen.setObjectName("actionBild_ffnen")
        self.actionBeenden = QtWidgets.QAction(MainWindow)
        self.actionBeenden.setObjectName("actionBeenden")
        self.actionOpen_Image = QtWidgets.QAction(MainWindow)
        self.actionOpen_Image.setObjectName("actionOpen_Image")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionCrop_Images = QtWidgets.QAction(MainWindow)
        self.actionCrop_Images.setObjectName("actionCrop_Images")
        self.actionExtract_Features = QtWidgets.QAction(MainWindow)
        self.actionExtract_Features.setObjectName("actionExtract_Features")
        self.actionSettings = QtWidgets.QAction(MainWindow)
        self.actionSettings.setObjectName("actionSettings")
        self.menuDatei.addAction(self.actionOpen_Image)
        self.menuDatei.addAction(self.actionSettings)
        self.menuDatei.addSeparator()
        self.menuDatei.addAction(self.actionExit)
        self.menuBatch.addAction(self.actionCrop_Images)
        self.menuBatch.addAction(self.actionExtract_Features)
        self.menubar.addAction(self.menuDatei.menuAction())
        self.menubar.addAction(self.menuBatch.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.preprocess_button.setText(_translate("MainWindow", "Preprocess"))
        self.source_label.setText(_translate("MainWindow", "Image not found"))
        self.feature_label.setText(_translate("MainWindow", "Image not found"))
        self.pushButton_3.setText(_translate("MainWindow", "Extract"))
        self.label_6.setText(_translate("MainWindow", "Preprocessing"))
        self.label_5.setText(_translate("MainWindow", "Source Image"))
        self.preprocess_label.setText(_translate("MainWindow", "Image not found"))
        self.label_7.setText(_translate("MainWindow", "Features"))
        self.open_source_button.setText(_translate("MainWindow", "Open"))
        self.label_8.setText(_translate("MainWindow", "↑↑↑ drag & drop"))
        self.label_4.setText(_translate("MainWindow", "Zoom"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.preprocessing_tab), _translate("MainWindow", "Preprocessing/Features"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Plot selected Features/Species"))
        self.pushButton_2.setText(_translate("MainWindow", "Plot ????"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Train selected Features/Species"))
        self.train_button.setText(_translate("MainWindow", "Train and save"))
        self.label_3.setText(_translate("MainWindow", "Classifier"))
        self.groupBox.setTitle(_translate("MainWindow", "Features"))
        self.delete_button.setText(_translate("MainWindow", "Delete"))
        self.label.setText(_translate("MainWindow", "Available species"))
        self.label_2.setText(_translate("MainWindow", "Features to train"))
        self.checkBox_2.setText(_translate("MainWindow", "select/deselect  all"))
        self.checkBox.setText(_translate("MainWindow", "select/deselect  all"))
        self.pushButton_4.setText(_translate("MainWindow", "Delete"))
        self.add_feature_button.setText(_translate("MainWindow", "Extract Features"))
        self.groupBox_4.setTitle(_translate("MainWindow", "GroupBox"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.training_tab), _translate("MainWindow", "Training"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.prediction_tab), _translate("MainWindow", "Prediction"))
        self.menuDatei.setTitle(_translate("MainWindow", "File"))
        self.menuBatch.setTitle(_translate("MainWindow", "Batch"))
        self.actionBild_ffnen.setText(_translate("MainWindow", "Bild öffnen"))
        self.actionBeenden.setText(_translate("MainWindow", "Beenden"))
        self.actionOpen_Image.setText(_translate("MainWindow", "Open Image"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionCrop_Images.setText(_translate("MainWindow", "Crop Images"))
        self.actionExtract_Features.setText(_translate("MainWindow", "Extract Features"))
        self.actionSettings.setText(_translate("MainWindow", "Settings"))

