# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt/main_window.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1092, 591)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setObjectName("tabWidget")
        self.preprocessing_tab = QtWidgets.QWidget()
        self.preprocessing_tab.setObjectName("preprocessing_tab")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.preprocessing_tab)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.preprocessor_combo = QtWidgets.QComboBox(self.preprocessing_tab)
        self.preprocessor_combo.setObjectName("preprocessor_combo")
        self.gridLayout_4.addWidget(self.preprocessor_combo, 0, 5, 1, 1)
        self.preprocess_button = QtWidgets.QPushButton(self.preprocessing_tab)
        self.preprocess_button.setObjectName("preprocess_button")
        self.gridLayout_4.addWidget(self.preprocess_button, 0, 6, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem, 1, 0, 1, 1)
        self.zoom_slider = QtWidgets.QSlider(self.preprocessing_tab)
        self.zoom_slider.setMinimum(1)
        self.zoom_slider.setMaximum(50)
        self.zoom_slider.setOrientation(QtCore.Qt.Vertical)
        self.zoom_slider.setObjectName("zoom_slider")
        self.gridLayout_4.addWidget(self.zoom_slider, 1, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem1, 1, 2, 1, 1)
        self.source_image_scroll = QtWidgets.QScrollArea(self.preprocessing_tab)
        self.source_image_scroll.setMinimumSize(QtCore.QSize(300, 300))
        self.source_image_scroll.setWidgetResizable(True)
        self.source_image_scroll.setObjectName("source_image_scroll")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 402, 359))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.source_label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.source_label.setAlignment(QtCore.Qt.AlignCenter)
        self.source_label.setObjectName("source_label")
        self.gridLayout.addWidget(self.source_label, 0, 1, 1, 1)
        self.source_image_scroll.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_4.addWidget(self.source_image_scroll, 1, 3, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem2, 1, 4, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(self.preprocessing_tab)
        self.scrollArea.setMinimumSize(QtCore.QSize(300, 300))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 483, 359))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.preprocess_label = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.preprocess_label.setAlignment(QtCore.Qt.AlignCenter)
        self.preprocess_label.setObjectName("preprocess_label")
        self.gridLayout_3.addWidget(self.preprocess_label, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout_4.addWidget(self.scrollArea, 1, 5, 1, 2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem3, 1, 7, 1, 1)
        self.preprocess_combo = QtWidgets.QComboBox(self.preprocessing_tab)
        self.preprocess_combo.setObjectName("preprocess_combo")
        self.gridLayout_4.addWidget(self.preprocess_combo, 2, 5, 1, 2)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem4, 3, 5, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_4.addItem(spacerItem5, 4, 3, 1, 3)
        self.tabWidget.addTab(self.preprocessing_tab, "")
        self.training_tab = QtWidgets.QWidget()
        self.training_tab.setObjectName("training_tab")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.training_tab)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.classifier_combo = QtWidgets.QComboBox(self.training_tab)
        self.classifier_combo.setObjectName("classifier_combo")
        self.gridLayout_5.addWidget(self.classifier_combo, 0, 0, 1, 2)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem6, 0, 3, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.training_tab)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_5.addWidget(self.pushButton, 3, 3, 1, 1)
        self.line = QtWidgets.QFrame(self.training_tab)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_5.addWidget(self.line, 0, 2, 4, 1)
        self.scrollArea_2 = QtWidgets.QScrollArea(self.training_tab)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 274, 460))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_3)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.listView = QtWidgets.QListView(self.scrollAreaWidgetContents_3)
        self.listView.setObjectName("listView")
        self.gridLayout_6.addWidget(self.listView, 1, 0, 1, 3)
        self.pushButton_2 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_6.addWidget(self.pushButton_2, 3, 2, 1, 1)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.scrollAreaWidgetContents_3)
        self.plainTextEdit.setMaximumSize(QtCore.QSize(16777215, 150))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.gridLayout_6.addWidget(self.plainTextEdit, 0, 0, 1, 3)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem7, 3, 0, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_6.addWidget(self.pushButton_3, 3, 1, 1, 1)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_3)
        self.gridLayout_5.addWidget(self.scrollArea_2, 1, 0, 3, 2)
        self.tabWidget.addTab(self.training_tab, "")
        self.gridLayout_2.addWidget(self.tabWidget, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1092, 21))
        self.menubar.setObjectName("menubar")
        self.menuDatei = QtWidgets.QMenu(self.menubar)
        self.menuDatei.setObjectName("menuDatei")
        self.menuBatch = QtWidgets.QMenu(self.menubar)
        self.menuBatch.setObjectName("menuBatch")
        self.menuTraining = QtWidgets.QMenu(self.menubar)
        self.menuTraining.setObjectName("menuTraining")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionBild_ffnen = QtWidgets.QAction(MainWindow)
        self.actionBild_ffnen.setObjectName("actionBild_ffnen")
        self.actionBeenden = QtWidgets.QAction(MainWindow)
        self.actionBeenden.setObjectName("actionBeenden")
        self.actionOpen_Image = QtWidgets.QAction(MainWindow)
        self.actionOpen_Image.setObjectName("actionOpen_Image")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionCrop_Images = QtWidgets.QAction(MainWindow)
        self.actionCrop_Images.setObjectName("actionCrop_Images")
        self.actionExtract_Features = QtWidgets.QAction(MainWindow)
        self.actionExtract_Features.setObjectName("actionExtract_Features")
        self.menuDatei.addAction(self.actionOpen_Image)
        self.menuDatei.addSeparator()
        self.menuDatei.addAction(self.actionExit)
        self.menuBatch.addAction(self.actionCrop_Images)
        self.menuBatch.addAction(self.actionExtract_Features)
        self.menubar.addAction(self.menuDatei.menuAction())
        self.menubar.addAction(self.menuBatch.menuAction())
        self.menubar.addAction(self.menuTraining.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.preprocess_button.setText(_translate("MainWindow", "Preprocess"))
        self.source_label.setText(_translate("MainWindow", "Image not found"))
        self.preprocess_label.setText(_translate("MainWindow", "Image not found"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.preprocessing_tab), _translate("MainWindow", "Preprocessing"))
        self.pushButton.setText(_translate("MainWindow", "Train"))
        self.pushButton_2.setText(_translate("MainWindow", "Load"))
        self.pushButton_3.setText(_translate("MainWindow", "New"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.training_tab), _translate("MainWindow", "Training"))
        self.menuDatei.setTitle(_translate("MainWindow", "File"))
        self.menuBatch.setTitle(_translate("MainWindow", "Batch"))
        self.menuTraining.setTitle(_translate("MainWindow", "Training"))
        self.actionBild_ffnen.setText(_translate("MainWindow", "Bild öffnen"))
        self.actionBeenden.setText(_translate("MainWindow", "Beenden"))
        self.actionOpen_Image.setText(_translate("MainWindow", "Open Image"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionCrop_Images.setText(_translate("MainWindow", "Crop Images"))
        self.actionExtract_Features.setText(_translate("MainWindow", "Extract Features"))

